version: "3"
services:
  api:
    container_name: app
    build:
      context: .
    volumes:
      - .:/src/app
      - /src/app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    ports:
      - 5000:5000
    command: ["npm", "start"]
